devices: 1
epochs: 1000
download: True
data_dir:

data:
    train:
        dataset:
            root: ${data_dir}
            train: True
            download: ${download}
        dataloader:
            batch_size: 128
            num_workers: 8
            drop_last: True
            pin_memory: True
            shuffle: True
            
    val:
        dataset:
            root: ${data_dir}
            train: False
            download: False
        dataloader:
            batch_size: 128
            num_workers: 8
            drop_last: False
            pin_memory: True
            shuffle: False
        
        
model:
    args:
        vq_flavor: 'vqvae' # 'vqvae' or 'gumbel'
        enc_dec_flavor: 'deepmind' # 'deepmind' or 'openai'
        loss_flavor: 'l2' # 'l2' or 'logit_laplace'
        num_embeddings: 512
        embedding_dim: 64
        n_hid: 64
    

trainer:
    devices: ${devices}
    max_epochs: ${epochs}
    check_val_every_n_epoch: 1