devices: 1
epochs: 500
download: True
data_dir:

defaults:    
    - dataset: cifar10
        
model:
    name: 'SimpleVQVAE'
    args:
        encoder:
            input_dim: ${dataset.img_channels} 
            hidden_dim: 128
            output_dim: ${model.args.encoder.hidden_dim}
        codebook:
            n_embeddings: 768
            embedding_dim: ${model.args.encoder.hidden_dim}
        decoder:
            input_dim: ${model.args.encoder.hidden_dim}
            hidden_dim: ${model.args.encoder.hidden_dim}
            output_dim: ${dataset.img_channels}
        
        
task:
    lr: 2e-4
    checkpoint:
        monitor: "Val/total_loss"
        filename: "{epoch:02d}"
        save_top_k: 2
        mode: "min"
        auto_insert_metric_name: False
        save_last: True
    
    
    

trainer:
    devices: ${devices}
    max_epochs: ${epochs}
    check_val_every_n_epoch: 1